version = 0.1

[default.deploy.parameters]
stack_name = "raktsetu-intelligence-dev"
resolve_s3 = true
s3_prefix = "raktsetu-intelligence"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Stage=dev PlannerMobilize=0"
image_repositories = []

[default.build.parameters]
cached = true
parallel = true
